variables:
  DOCKER_IMAGE: "laurentgrangeau/oc-devops:latest"

image: $DOCKER_IMAGE

stages:
  - build
  - test
  - quality
  - package
  - deploy

build:
  script:
    - mvn clean install

test:
  script:
    - mvn test

quality:
  script:
    - mvn sonar:sonar

package:
  script:
    - mvn clean install -DskipTests

deploy:
  script:
    - echo "**Déploiement non configuré**"
