stages:
  - compile
  - test
  - quality
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

compile:
  stage: compile
  image: laurentgrangeau/oc-devops:latest
  script:
    - ./mvnw compile $MAVEN_CLI_OPTS

test:
  stage: test
  image: laurentgrangeau/oc-devops:latest
  script:
    - ./mvnw test $MAVEN_CLI_OPTS

quality:
  stage: quality
  image: laurentgrangeau/oc-devops:latest
  script:
    - ./mvnw verify sonar:sonar $MAVEN_CLI_OPTS

deploy:
  stage: deploy
  image: laurentgrangeau/oc-devops:latest
  script:
    - ./mvnw deploy $MAVEN_CLI_OPTS
  only:
    - master
