version: '2'

services:
  config-server:
    image: registry.gitlab.com/patvc15/spring-petclinic-config-server:3.0.2
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: registry.gitlab.com/patvc15/spring-petclinic-discovery-server:3.0.2
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761
